// Copyright IBM Corp. 2022, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: types/github.com.hashicorp.nodeenrollment.types.v1.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KEYTYPE is an enum holding known key types
type KEYTYPE int32

const (
	KEYTYPE_UNSPECIFIED KEYTYPE = 0
	KEYTYPE_ED25519     KEYTYPE = 1
	KEYTYPE_X25519      KEYTYPE = 2
)

// Enum value maps for KEYTYPE.
var (
	KEYTYPE_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ED25519",
		2: "X25519",
	}
	KEYTYPE_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ED25519":     1,
		"X25519":      2,
	}
)

func (x KEYTYPE) Enum() *KEYTYPE {
	p := new(KEYTYPE)
	*p = x
	return p
}

func (x KEYTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KEYTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_enumTypes[0].Descriptor()
}

func (KEYTYPE) Type() protoreflect.EnumType {
	return &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_enumTypes[0]
}

func (x KEYTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KEYTYPE.Descriptor instead.
func (KEYTYPE) EnumDescriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{0}
}

// CertificateBundle contains information about a certificate the its issuing
// certificate
type CertificateBundle struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CertificateDer       []byte                 `protobuf:"bytes,1,opt,name=certificate_der,proto3" json:"certificate_der,omitempty"`
	CaCertificateDer     []byte                 `protobuf:"bytes,2,opt,name=ca_certificate_der,proto3" json:"ca_certificate_der,omitempty"`
	CertificateNotBefore *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=certificate_not_before,proto3" json:"certificate_not_before,omitempty"`
	CertificateNotAfter  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=certificate_not_after,proto3" json:"certificate_not_after,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CertificateBundle) Reset() {
	*x = CertificateBundle{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateBundle) ProtoMessage() {}

func (x *CertificateBundle) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateBundle.ProtoReflect.Descriptor instead.
func (*CertificateBundle) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateBundle) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *CertificateBundle) GetCaCertificateDer() []byte {
	if x != nil {
		return x.CaCertificateDer
	}
	return nil
}

func (x *CertificateBundle) GetCertificateNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CertificateNotBefore
	}
	return nil
}

func (x *CertificateBundle) GetCertificateNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CertificateNotAfter
	}
	return nil
}

// RootCertificate contains information about a root CA certificate and its
// associated public/private keys
type RootCertificate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "current" or "next"
	PublicKeyPkix   []byte                 `protobuf:"bytes,2,opt,name=public_key_pkix,proto3" json:"public_key_pkix,omitempty"`
	PrivateKeyPkcs8 []byte                 `protobuf:"bytes,4,opt,name=private_key_pkcs8,proto3" json:"private_key_pkcs8,omitempty"`
	PrivateKeyType  KEYTYPE                `protobuf:"varint,5,opt,name=private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"private_key_type,omitempty"`
	CertificateDer  []byte                 `protobuf:"bytes,6,opt,name=certificate_der,proto3" json:"certificate_der,omitempty"`
	NotBefore       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,proto3" json:"not_before,omitempty"`
	NotAfter        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,proto3" json:"not_after,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RootCertificate) Reset() {
	*x = RootCertificate{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCertificate) ProtoMessage() {}

func (x *RootCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCertificate.ProtoReflect.Descriptor instead.
func (*RootCertificate) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RootCertificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RootCertificate) GetPublicKeyPkix() []byte {
	if x != nil {
		return x.PublicKeyPkix
	}
	return nil
}

func (x *RootCertificate) GetPrivateKeyPkcs8() []byte {
	if x != nil {
		return x.PrivateKeyPkcs8
	}
	return nil
}

func (x *RootCertificate) GetPrivateKeyType() KEYTYPE {
	if x != nil {
		return x.PrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *RootCertificate) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *RootCertificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *RootCertificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

// RootCertificates is a message that holds two root certificates for easy
// usage/identification. The ID will always be "roots".
type RootCertificates struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Current *RootCertificate       `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	Next    *RootCertificate       `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// If set, the key ID of the wrapping key used to encrypt the private key
	WrappingKeyId string `protobuf:"bytes,30,opt,name=wrapping_key_id,proto3" json:"wrapping_key_id,omitempty"`
	// State is data that the implementor of a Store can use to round-trip data
	// through this library; as an example, a version number on the resource for
	// implementing transactions.
	State         *structpb.Struct `protobuf:"bytes,50,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCertificates) Reset() {
	*x = RootCertificates{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCertificates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCertificates) ProtoMessage() {}

func (x *RootCertificates) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCertificates.ProtoReflect.Descriptor instead.
func (*RootCertificates) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RootCertificates) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RootCertificates) GetCurrent() *RootCertificate {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *RootCertificates) GetNext() *RootCertificate {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *RootCertificates) GetWrappingKeyId() string {
	if x != nil {
		return x.WrappingKeyId
	}
	return ""
}

func (x *RootCertificates) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

// EncryptionKey contains the key information necessary to generate a sharedKey
// NodeInformation and NodeCredentials will store their previous encryption key
// using this message type
type EncryptionKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyId           string                 `protobuf:"bytes,1,opt,name=key_id,proto3" json:"key_id,omitempty"`
	PrivateKeyPkcs8 []byte                 `protobuf:"bytes,2,opt,name=private_key_pkcs8,proto3" json:"private_key_pkcs8,omitempty"`
	PrivateKeyType  KEYTYPE                `protobuf:"varint,3,opt,name=private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"private_key_type,omitempty"`
	PublicKeyPkix   []byte                 `protobuf:"bytes,4,opt,name=public_key_pkix,proto3" json:"public_key_pkix,omitempty"`
	PublicKeyType   KEYTYPE                `protobuf:"varint,5,opt,name=public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"public_key_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EncryptionKey) Reset() {
	*x = EncryptionKey{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionKey) ProtoMessage() {}

func (x *EncryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionKey.ProtoReflect.Descriptor instead.
func (*EncryptionKey) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptionKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EncryptionKey) GetPrivateKeyPkcs8() []byte {
	if x != nil {
		return x.PrivateKeyPkcs8
	}
	return nil
}

func (x *EncryptionKey) GetPrivateKeyType() KEYTYPE {
	if x != nil {
		return x.PrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *EncryptionKey) GetPublicKeyPkix() []byte {
	if x != nil {
		return x.PublicKeyPkix
	}
	return nil
}

func (x *EncryptionKey) GetPublicKeyType() KEYTYPE {
	if x != nil {
		return x.PublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

// NodeInformation contains server-side information about a node: its
// certificate public key, any issued certificates (purely for informational
// purposes), its encryption public key and the corresponding server private
// key. Nonce may or may not have a value depending on the flow used to register
// the node and the current state of that flow. The first seen value can be
// useful for display to an operator looking to authorize a node. Authorized
// stores whether or not this node is authorized; technically we could derive
// this based on whether we have complete key/certificate information, but it's
// nice to be explicit.
//
// The ID corresponds to a key identifier generated by this library's
// KeyIdFromPkix function; unlike RootCertificate or NodeCredentials, which will
// only have at most two active values, here we need to identify an incoming
// node's information so use the actual key ID. Rotation simply means a new
// entry will be added with the new ID.
//
// NodeId is an external identifier for this node that does not change
type NodeInformation struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CertificatePublicKeyPkix         []byte                 `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	CertificatePublicKeyType         KEYTYPE                `protobuf:"varint,3,opt,name=certificate_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"certificate_public_key_type,omitempty"`
	CertificateBundles               []*CertificateBundle   `protobuf:"bytes,6,rep,name=certificate_bundles,proto3" json:"certificate_bundles,omitempty"`
	NodeId                           string                 `protobuf:"bytes,7,opt,name=node_id,proto3" json:"node_id,omitempty"`
	PreviousCertificatePublicKeyPkix []byte                 `protobuf:"bytes,9,opt,name=previous_certificate_public_key_pkix,proto3" json:"previous_certificate_public_key_pkix,omitempty"`
	EncryptionPublicKeyBytes         []byte                 `protobuf:"bytes,10,opt,name=encryption_public_key_bytes,proto3" json:"encryption_public_key_bytes,omitempty"`
	EncryptionPublicKeyType          KEYTYPE                `protobuf:"varint,11,opt,name=encryption_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"encryption_public_key_type,omitempty"`
	ServerEncryptionPrivateKeyBytes  []byte                 `protobuf:"bytes,12,opt,name=server_encryption_private_key_bytes,proto3" json:"server_encryption_private_key_bytes,omitempty"`
	ServerEncryptionPrivateKeyType   KEYTYPE                `protobuf:"varint,13,opt,name=server_encryption_private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"server_encryption_private_key_type,omitempty"`
	RegistrationNonce                []byte                 `protobuf:"bytes,20,opt,name=registration_nonce,proto3" json:"registration_nonce,omitempty"`
	RegistrationChallenge            *RegistrationChallenge `protobuf:"bytes,23,opt,name=registration_challenge,proto3" json:"registration_challenge,omitempty"`
	// This will be populated with with any decrypted values that came in as a
	// result of this flow
	WrappingRegistrationFlowInfo *WrappingRegistrationFlowInfo `protobuf:"bytes,22,opt,name=wrapping_registration_flow_info,proto3" json:"wrapping_registration_flow_info,omitempty"`
	// If set, the key ID of the wrapping key used to encrypt the private key and
	// the nonce
	WrappingKeyId string `protobuf:"bytes,30,opt,name=wrapping_key_id,proto3" json:"wrapping_key_id,omitempty"`
	// State is data that the implementor of a Store can use to round-trip data
	// through this library; as an example, a version number on the resource for
	// implementing transactions.
	State                 *structpb.Struct `protobuf:"bytes,50,opt,name=state,proto3" json:"state,omitempty"`
	PreviousEncryptionKey *EncryptionKey   `protobuf:"bytes,60,opt,name=previous_encryption_key,proto3" json:"previous_encryption_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeInformation) Reset() {
	*x = NodeInformation{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInformation) ProtoMessage() {}

func (x *NodeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInformation.ProtoReflect.Descriptor instead.
func (*NodeInformation) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInformation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInformation) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *NodeInformation) GetCertificatePublicKeyType() KEYTYPE {
	if x != nil {
		return x.CertificatePublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeInformation) GetCertificateBundles() []*CertificateBundle {
	if x != nil {
		return x.CertificateBundles
	}
	return nil
}

func (x *NodeInformation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInformation) GetPreviousCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.PreviousCertificatePublicKeyPkix
	}
	return nil
}

func (x *NodeInformation) GetEncryptionPublicKeyBytes() []byte {
	if x != nil {
		return x.EncryptionPublicKeyBytes
	}
	return nil
}

func (x *NodeInformation) GetEncryptionPublicKeyType() KEYTYPE {
	if x != nil {
		return x.EncryptionPublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeInformation) GetServerEncryptionPrivateKeyBytes() []byte {
	if x != nil {
		return x.ServerEncryptionPrivateKeyBytes
	}
	return nil
}

func (x *NodeInformation) GetServerEncryptionPrivateKeyType() KEYTYPE {
	if x != nil {
		return x.ServerEncryptionPrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeInformation) GetRegistrationNonce() []byte {
	if x != nil {
		return x.RegistrationNonce
	}
	return nil
}

func (x *NodeInformation) GetRegistrationChallenge() *RegistrationChallenge {
	if x != nil {
		return x.RegistrationChallenge
	}
	return nil
}

func (x *NodeInformation) GetWrappingRegistrationFlowInfo() *WrappingRegistrationFlowInfo {
	if x != nil {
		return x.WrappingRegistrationFlowInfo
	}
	return nil
}

func (x *NodeInformation) GetWrappingKeyId() string {
	if x != nil {
		return x.WrappingKeyId
	}
	return ""
}

func (x *NodeInformation) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *NodeInformation) GetPreviousEncryptionKey() *EncryptionKey {
	if x != nil {
		return x.PreviousEncryptionKey
	}
	return nil
}

// NodeInformationSet is a message that holds multiple NodeInformation entries
// for a node. This is used to load all valid NodeInformation entries for a node
// from storage and can be used in situations where failover to previous
// credentials is necessary.
//
// NodeId is an external identifier for this node that does not change
type NodeInformationSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,proto3" json:"node_id,omitempty"`
	Nodes         []*NodeInformation     `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInformationSet) Reset() {
	*x = NodeInformationSet{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInformationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInformationSet) ProtoMessage() {}

func (x *NodeInformationSet) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInformationSet.ProtoReflect.Descriptor instead.
func (*NodeInformationSet) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInformationSet) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInformationSet) GetNodes() []*NodeInformation {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// RegistrationChallenge is a challenge issued by one side to the other for authentication.
type RegistrationChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationChallenge) Reset() {
	*x = RegistrationChallenge{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationChallenge) ProtoMessage() {}

func (x *RegistrationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationChallenge.ProtoReflect.Descriptor instead.
func (*RegistrationChallenge) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationChallenge) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// NodeCredentials is the corresponding struct for NodeInformation on the node
// side, containing the values necessary for proving identity. At various points
// in registration/authorization flows this may have some or all fields filled in.
type NodeCredentials struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "current" or "next"
	CertificatePublicKeyPkix         []byte                 `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	CertificatePrivateKeyPkcs8       []byte                 `protobuf:"bytes,4,opt,name=certificate_private_key_pkcs8,proto3" json:"certificate_private_key_pkcs8,omitempty"`
	CertificatePrivateKeyType        KEYTYPE                `protobuf:"varint,5,opt,name=certificate_private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"certificate_private_key_type,omitempty"`
	CertificateBundles               []*CertificateBundle   `protobuf:"bytes,6,rep,name=certificate_bundles,proto3" json:"certificate_bundles,omitempty"`
	PreviousCertificatePublicKeyPkix []byte                 `protobuf:"bytes,9,opt,name=previous_certificate_public_key_pkix,proto3" json:"previous_certificate_public_key_pkix,omitempty"`
	EncryptionPrivateKeyBytes        []byte                 `protobuf:"bytes,10,opt,name=encryption_private_key_bytes,proto3" json:"encryption_private_key_bytes,omitempty"`
	EncryptionPrivateKeyType         KEYTYPE                `protobuf:"varint,11,opt,name=encryption_private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"encryption_private_key_type,omitempty"`
	ServerEncryptionPublicKeyBytes   []byte                 `protobuf:"bytes,12,opt,name=server_encryption_public_key_bytes,proto3" json:"server_encryption_public_key_bytes,omitempty"`
	ServerEncryptionPublicKeyType    KEYTYPE                `protobuf:"varint,13,opt,name=server_encryption_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"server_encryption_public_key_type,omitempty"`
	RegistrationNonce                []byte                 `protobuf:"bytes,20,opt,name=registration_nonce,proto3" json:"registration_nonce,omitempty"`
	RegistrationChallenge            *RegistrationChallenge `protobuf:"bytes,23,opt,name=registration_challenge,proto3" json:"registration_challenge,omitempty"`
	EncryptedRegistrationChallenge   []byte                 `protobuf:"bytes,24,opt,name=encrypted_registration_challenge,proto3" json:"encrypted_registration_challenge,omitempty"`
	// If set, the key ID of the wrapping key used to encrypt the private keys
	WrappingKeyId string `protobuf:"bytes,30,opt,name=wrapping_key_id,proto3" json:"wrapping_key_id,omitempty"`
	// State is data that the implementor of a Store can use to round-trip data
	// through this library; as an example, a version number on the resource for
	// implementing transactions.
	State                 *structpb.Struct `protobuf:"bytes,50,opt,name=state,proto3" json:"state,omitempty"`
	PreviousEncryptionKey *EncryptionKey   `protobuf:"bytes,60,opt,name=previous_encryption_key,proto3" json:"previous_encryption_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeCredentials) Reset() {
	*x = NodeCredentials{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCredentials) ProtoMessage() {}

func (x *NodeCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCredentials.ProtoReflect.Descriptor instead.
func (*NodeCredentials) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{7}
}

func (x *NodeCredentials) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeCredentials) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *NodeCredentials) GetCertificatePrivateKeyPkcs8() []byte {
	if x != nil {
		return x.CertificatePrivateKeyPkcs8
	}
	return nil
}

func (x *NodeCredentials) GetCertificatePrivateKeyType() KEYTYPE {
	if x != nil {
		return x.CertificatePrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeCredentials) GetCertificateBundles() []*CertificateBundle {
	if x != nil {
		return x.CertificateBundles
	}
	return nil
}

func (x *NodeCredentials) GetPreviousCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.PreviousCertificatePublicKeyPkix
	}
	return nil
}

func (x *NodeCredentials) GetEncryptionPrivateKeyBytes() []byte {
	if x != nil {
		return x.EncryptionPrivateKeyBytes
	}
	return nil
}

func (x *NodeCredentials) GetEncryptionPrivateKeyType() KEYTYPE {
	if x != nil {
		return x.EncryptionPrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeCredentials) GetServerEncryptionPublicKeyBytes() []byte {
	if x != nil {
		return x.ServerEncryptionPublicKeyBytes
	}
	return nil
}

func (x *NodeCredentials) GetServerEncryptionPublicKeyType() KEYTYPE {
	if x != nil {
		return x.ServerEncryptionPublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *NodeCredentials) GetRegistrationNonce() []byte {
	if x != nil {
		return x.RegistrationNonce
	}
	return nil
}

func (x *NodeCredentials) GetRegistrationChallenge() *RegistrationChallenge {
	if x != nil {
		return x.RegistrationChallenge
	}
	return nil
}

func (x *NodeCredentials) GetEncryptedRegistrationChallenge() []byte {
	if x != nil {
		return x.EncryptedRegistrationChallenge
	}
	return nil
}

func (x *NodeCredentials) GetWrappingKeyId() string {
	if x != nil {
		return x.WrappingKeyId
	}
	return ""
}

func (x *NodeCredentials) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *NodeCredentials) GetPreviousEncryptionKey() *EncryptionKey {
	if x != nil {
		return x.PreviousEncryptionKey
	}
	return nil
}

// WrappingRegistrationFlowInfo is a message that can be encrypted via a shared
// encryption wrapper and supplied to perform just-in-time registration. The
// public key contained in this bundle must match that within
// FetchNodeCredentialsInfo, as must the nonce. Forgeries by other users with
// access to the wrapper are prevented due to the signature on the
// FetchNodeCredentialsRequest including this; replays are prevented because the
// returned credentials are still encrypted to the derived shared key.
//
// The application specific params can be used to pass extra registration
// information to the consuming application. Although both provide state to the
// server, there are two differences between the application specific params and
// passing state through to the node's dialer:
//
//   - The information is available at different times; client state cannot be
//     sent through most of the nodeenrollment code because state parameters are
//     reserved for the storage system to use as needed (e.g. to track operations
//     across multiple calls). So client state is only available to the eventual
//     receiver of a connection via a *protocol.Conn, whereas the application
//     specific params are available when node information is being stored (at
//     which time a conn is not available, and where passing this information as
//     state would overwrite the storage system's state, if used).
//   - Anything in WrappingRegistrationFlowInfo is encrypted via the KMS, if
//     required
//
// It is entirely possible that the state passed into `protocol.Dial` and
// application specific params will carry the same data for use at different
// times. For instance, information about a node's name and version may be put
// into application specific params in order to have it avaialble during
// registration time, since registration is automatic (as opposed to e.g. an API
// call to activate a worker-led token where name can be provided at that time);
// however, when the connection is eventually returned to the application
// listener, the state can help the application figure out the next step in
// handling the connection based on version (e.g. passing to gRPC versus
// starting a yamux session).
type WrappingRegistrationFlowInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CertificatePublicKeyPkix  []byte                 `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	Nonce                     []byte                 `protobuf:"bytes,20,opt,name=nonce,proto3" json:"nonce,omitempty"`
	RegistrationChallenge     []byte                 `protobuf:"bytes,23,opt,name=registration_challenge,proto3" json:"registration_challenge,omitempty"`
	ApplicationSpecificParams *structpb.Struct       `protobuf:"bytes,50,opt,name=application_specific_params,json=applicationSpecificParams,proto3" json:"application_specific_params,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WrappingRegistrationFlowInfo) Reset() {
	*x = WrappingRegistrationFlowInfo{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappingRegistrationFlowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappingRegistrationFlowInfo) ProtoMessage() {}

func (x *WrappingRegistrationFlowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappingRegistrationFlowInfo.ProtoReflect.Descriptor instead.
func (*WrappingRegistrationFlowInfo) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{8}
}

func (x *WrappingRegistrationFlowInfo) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *WrappingRegistrationFlowInfo) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *WrappingRegistrationFlowInfo) GetRegistrationChallenge() []byte {
	if x != nil {
		return x.RegistrationChallenge
	}
	return nil
}

func (x *WrappingRegistrationFlowInfo) GetApplicationSpecificParams() *structpb.Struct {
	if x != nil {
		return x.ApplicationSpecificParams
	}
	return nil
}

// FetchNodeCredentialsInfo contains the values bundled and signed into a
// FetchNodeCredentialsRequest. These values contain the ID (for identification,
// although the server should always re-derive this itself), the claimed
// certificate public key (which is also used to sign these values), and the
// public encryption key, as well as the registration nonce.
//
// Because the signature from the certificate public key is across both itself
// and the encryption key, if the key ID is authorized, then after verification
// of the signature we can trust the public encryption key too, which is an
// important property for preventing MITM/replay scenarios.
type FetchNodeCredentialsInfo struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Key id derived from pkix public key
	CertificatePublicKeyPkix         []byte                 `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	CertificatePublicKeyType         KEYTYPE                `protobuf:"varint,3,opt,name=certificate_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"certificate_public_key_type,omitempty"`
	PreviousCertificatePublicKeyPkix []byte                 `protobuf:"bytes,9,opt,name=previous_certificate_public_key_pkix,proto3" json:"previous_certificate_public_key_pkix,omitempty"`
	EncryptionPublicKeyBytes         []byte                 `protobuf:"bytes,10,opt,name=encryption_public_key_bytes,proto3" json:"encryption_public_key_bytes,omitempty"`
	EncryptionPublicKeyType          KEYTYPE                `protobuf:"varint,11,opt,name=encryption_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"encryption_public_key_type,omitempty"`
	Nonce                            []byte                 `protobuf:"bytes,20,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Used in node-led as part of the activation token
	RegistrationChallenge *RegistrationChallenge `protobuf:"bytes,23,opt,name=registration_challenge,proto3" json:"registration_challenge,omitempty"`
	// Used in server-led for node to prove its identity
	EncryptedRegistrationChallenge []byte `protobuf:"bytes,24,opt,name=encrypted_registration_challenge,proto3" json:"encrypted_registration_challenge,omitempty"`
	ActivationTokenId              string `protobuf:"bytes,25,opt,name=activation_token_id,proto3" json:"activation_token_id,omitempty"`
	// If provided, a wrapped (encrypted) registration bundle that can be used for
	// just-in-time authorization
	WrappedRegistrationInfo []byte `protobuf:"bytes,21,opt,name=wrapped_registration_info,proto3" json:"wrapped_registration_info,omitempty"`
	// This will be populated with decrypted values if the above field is populated
	WrappingRegistrationFlowInfo *WrappingRegistrationFlowInfo `protobuf:"bytes,22,opt,name=wrapping_registration_flow_info,proto3" json:"wrapping_registration_flow_info,omitempty"`
	NotBefore                    *timestamppb.Timestamp        `protobuf:"bytes,7,opt,name=not_before,proto3" json:"not_before,omitempty"`
	NotAfter                     *timestamppb.Timestamp        `protobuf:"bytes,8,opt,name=not_after,proto3" json:"not_after,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *FetchNodeCredentialsInfo) Reset() {
	*x = FetchNodeCredentialsInfo{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNodeCredentialsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNodeCredentialsInfo) ProtoMessage() {}

func (x *FetchNodeCredentialsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNodeCredentialsInfo.ProtoReflect.Descriptor instead.
func (*FetchNodeCredentialsInfo) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{9}
}

func (x *FetchNodeCredentialsInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FetchNodeCredentialsInfo) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetCertificatePublicKeyType() KEYTYPE {
	if x != nil {
		return x.CertificatePublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *FetchNodeCredentialsInfo) GetPreviousCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.PreviousCertificatePublicKeyPkix
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetEncryptionPublicKeyBytes() []byte {
	if x != nil {
		return x.EncryptionPublicKeyBytes
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetEncryptionPublicKeyType() KEYTYPE {
	if x != nil {
		return x.EncryptionPublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *FetchNodeCredentialsInfo) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetRegistrationChallenge() *RegistrationChallenge {
	if x != nil {
		return x.RegistrationChallenge
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetEncryptedRegistrationChallenge() []byte {
	if x != nil {
		return x.EncryptedRegistrationChallenge
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetActivationTokenId() string {
	if x != nil {
		return x.ActivationTokenId
	}
	return ""
}

func (x *FetchNodeCredentialsInfo) GetWrappedRegistrationInfo() []byte {
	if x != nil {
		return x.WrappedRegistrationInfo
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetWrappingRegistrationFlowInfo() *WrappingRegistrationFlowInfo {
	if x != nil {
		return x.WrappingRegistrationFlowInfo
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *FetchNodeCredentialsInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

// FetchNodeCredentialsRequest contains the marshaled FetchNodeCredentialsInfo
// message and a signature using private key corresponding to the certificate
// public key contained within the marshaled bundle.
type FetchNodeCredentialsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bundle          []byte                 `protobuf:"bytes,28,opt,name=bundle,proto3" json:"bundle,omitempty"`
	BundleSignature []byte                 `protobuf:"bytes,29,opt,name=bundle_signature,proto3" json:"bundle_signature,omitempty"`
	// If an intermediate node is decrypting the wrapped registration info with a
	// wrapper not available on the server, it can't cache the decrypted value in
	// the original bundle because it's signed. In that case, it can cache the
	// value here and encrypt it to the server.
	RewrappedWrappingRegistrationFlowInfo []byte `protobuf:"bytes,32,opt,name=rewrapped_wrapping_registration_flow_info,proto3" json:"rewrapped_wrapping_registration_flow_info,omitempty"`
	RewrappingKeyId                       string `protobuf:"bytes,33,opt,name=rewrapping_key_id,proto3" json:"rewrapping_key_id,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *FetchNodeCredentialsRequest) Reset() {
	*x = FetchNodeCredentialsRequest{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNodeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNodeCredentialsRequest) ProtoMessage() {}

func (x *FetchNodeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNodeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*FetchNodeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{10}
}

func (x *FetchNodeCredentialsRequest) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *FetchNodeCredentialsRequest) GetBundleSignature() []byte {
	if x != nil {
		return x.BundleSignature
	}
	return nil
}

func (x *FetchNodeCredentialsRequest) GetRewrappedWrappingRegistrationFlowInfo() []byte {
	if x != nil {
		return x.RewrappedWrappingRegistrationFlowInfo
	}
	return nil
}

func (x *FetchNodeCredentialsRequest) GetRewrappingKeyId() string {
	if x != nil {
		return x.RewrappingKeyId
	}
	return ""
}

// FetchNodeCredentialsResponse contains a response to a fetch request. If
// unauthorized, only that bool will be returned. If authorized, the encrypted
// node credentials will contain a marshaled NodeCredentials struct containing
// certificates and other server-provided information, with the encryption key
// derived from a DH operation on the node's submitted public key and the
// server's private key corresponding to the given public encryption key.
//
// The encrypted node credentials are signed with the current root certificate
// key. This is an optional step that can be taken by the node if it has
// pre-distributed CA certificates to validate the signature on the encrypted
// node credentials. This mostly is a guard against the failure of an operator
// to actually validate the key ID that they are authorizing.
type FetchNodeCredentialsResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ServerEncryptionPublicKeyBytes []byte                 `protobuf:"bytes,12,opt,name=server_encryption_public_key_bytes,json=encryption_public_key_bytes,proto3" json:"server_encryption_public_key_bytes,omitempty"`
	ServerEncryptionPublicKeyType  KEYTYPE                `protobuf:"varint,13,opt,name=server_encryption_public_key_type,json=encryption_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"server_encryption_public_key_type,omitempty"`
	EncryptedNodeCredentials       []byte                 `protobuf:"bytes,40,opt,name=encrypted_node_credentials,proto3" json:"encrypted_node_credentials,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *FetchNodeCredentialsResponse) Reset() {
	*x = FetchNodeCredentialsResponse{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNodeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNodeCredentialsResponse) ProtoMessage() {}

func (x *FetchNodeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNodeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*FetchNodeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{11}
}

func (x *FetchNodeCredentialsResponse) GetServerEncryptionPublicKeyBytes() []byte {
	if x != nil {
		return x.ServerEncryptionPublicKeyBytes
	}
	return nil
}

func (x *FetchNodeCredentialsResponse) GetServerEncryptionPublicKeyType() KEYTYPE {
	if x != nil {
		return x.ServerEncryptionPublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *FetchNodeCredentialsResponse) GetEncryptedNodeCredentials() []byte {
	if x != nil {
		return x.EncryptedNodeCredentials
	}
	return nil
}

// RotateNodeCredentialsRequest is the message used when a node wants to rotate
// credentials
type RotateNodeCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For identification of the node, in case it's not trivial from the
	// connection
	CertificatePublicKeyPkix []byte `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	// NodeId is an external identifier for this node that does not change
	NodeId string `protobuf:"bytes,7,opt,name=node_id,proto3" json:"node_id,omitempty"`
	// Encrypted FetchNodeCredentialsRequest, with the current encryption
	// parameters used for key generation
	EncryptedFetchNodeCredentialsRequest []byte `protobuf:"bytes,45,opt,name=encrypted_fetch_node_credentials_request,proto3" json:"encrypted_fetch_node_credentials_request,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *RotateNodeCredentialsRequest) Reset() {
	*x = RotateNodeCredentialsRequest{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNodeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNodeCredentialsRequest) ProtoMessage() {}

func (x *RotateNodeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNodeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RotateNodeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{12}
}

func (x *RotateNodeCredentialsRequest) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *RotateNodeCredentialsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RotateNodeCredentialsRequest) GetEncryptedFetchNodeCredentialsRequest() []byte {
	if x != nil {
		return x.EncryptedFetchNodeCredentialsRequest
	}
	return nil
}

// RotateNodeCredentialsResponse is the message used to return values
type RotateNodeCredentialsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted FetchNodeCredentialsResponse, with the current encryption
	// parameters used for key generation. The new key will be used for the
	// encrypted node credentials in the response.
	EncryptedFetchNodeCredentialsResponse []byte `protobuf:"bytes,45,opt,name=encrypted_fetch_node_credentials_response,proto3" json:"encrypted_fetch_node_credentials_response,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *RotateNodeCredentialsResponse) Reset() {
	*x = RotateNodeCredentialsResponse{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNodeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNodeCredentialsResponse) ProtoMessage() {}

func (x *RotateNodeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNodeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RotateNodeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{13}
}

func (x *RotateNodeCredentialsResponse) GetEncryptedFetchNodeCredentialsResponse() []byte {
	if x != nil {
		return x.EncryptedFetchNodeCredentialsResponse
	}
	return nil
}

// GenerateServerCertificatesRequest holds values necessary for the server to
// generate a server-side TLS certificate, either for itself or for a middle
// node in a multi-hop scenario. The nonce and signature are provided by the
// authenticating node, so that the server can validate the signature and ensure
// that the node is authorized, then embed the nonce in the returned certificate
// to authorize the upstream node (or server) to the authenticating node.
//
// The common name and skip verification parameters would ideally be options to
// downstream functions, however, since multihop goes over gRPC (or could go
// over some other transport) the options cannot be carried in that way. If
// desired, in the future, an options message could be created and these (and
// any other) values aggregated there.
type GenerateServerCertificatesRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CertificatePublicKeyPkix []byte                 `protobuf:"bytes,2,opt,name=certificate_public_key_pkix,proto3" json:"certificate_public_key_pkix,omitempty"`
	// NodeId is an external identifier for this node that does not change
	NodeId           string `protobuf:"bytes,7,opt,name=node_id,proto3" json:"node_id,omitempty"`
	Nonce            []byte `protobuf:"bytes,20,opt,name=nonce,proto3" json:"nonce,omitempty"`
	NonceSignature   []byte `protobuf:"bytes,21,opt,name=nonce_signature,proto3" json:"nonce_signature,omitempty"`
	CommonName       string `protobuf:"bytes,24,opt,name=common_name,proto3" json:"common_name,omitempty"`
	SkipVerification bool   `protobuf:"varint,25,opt,name=skip_verification,proto3" json:"skip_verification,omitempty"`
	// ClientState data comes from the client and will be returned in the
	// *protocol.Conn, if used. This must be a marshaled structpb.Struct.
	ClientState []byte `protobuf:"bytes,50,opt,name=client_state,proto3" json:"client_state,omitempty"`
	// ClientStateSignature, like with the nonce, is used to be able to trust the
	// data, once the public key has been validated
	ClientStateSignature []byte `protobuf:"bytes,51,opt,name=client_state_signature,proto3" json:"client_state_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateServerCertificatesRequest) Reset() {
	*x = GenerateServerCertificatesRequest{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateServerCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateServerCertificatesRequest) ProtoMessage() {}

func (x *GenerateServerCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateServerCertificatesRequest.ProtoReflect.Descriptor instead.
func (*GenerateServerCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateServerCertificatesRequest) GetCertificatePublicKeyPkix() []byte {
	if x != nil {
		return x.CertificatePublicKeyPkix
	}
	return nil
}

func (x *GenerateServerCertificatesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GenerateServerCertificatesRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *GenerateServerCertificatesRequest) GetNonceSignature() []byte {
	if x != nil {
		return x.NonceSignature
	}
	return nil
}

func (x *GenerateServerCertificatesRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *GenerateServerCertificatesRequest) GetSkipVerification() bool {
	if x != nil {
		return x.SkipVerification
	}
	return false
}

func (x *GenerateServerCertificatesRequest) GetClientState() []byte {
	if x != nil {
		return x.ClientState
	}
	return nil
}

func (x *GenerateServerCertificatesRequest) GetClientStateSignature() []byte {
	if x != nil {
		return x.ClientStateSignature
	}
	return nil
}

// GenerateServerCertificatesResponse contains values for a successful response
// to the request: a private key for the server (or intemediate node) to use
// along with the returned certificates.
type GenerateServerCertificatesResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CertificatePrivateKeyPkcs8 []byte                 `protobuf:"bytes,4,opt,name=certificate_private_key_pkcs8,proto3" json:"certificate_private_key_pkcs8,omitempty"`
	CertificatePrivateKeyType  KEYTYPE                `protobuf:"varint,5,opt,name=certificate_private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"certificate_private_key_type,omitempty"`
	CertificateBundles         []*CertificateBundle   `protobuf:"bytes,6,rep,name=certificate_bundles,proto3" json:"certificate_bundles,omitempty"`
	// ClientState data is copied here from the request, if verified, and used to
	// populate the *protocol.Conn, if used
	ClientState   *structpb.Struct `protobuf:"bytes,50,opt,name=client_state,proto3" json:"client_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateServerCertificatesResponse) Reset() {
	*x = GenerateServerCertificatesResponse{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateServerCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateServerCertificatesResponse) ProtoMessage() {}

func (x *GenerateServerCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateServerCertificatesResponse.ProtoReflect.Descriptor instead.
func (*GenerateServerCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateServerCertificatesResponse) GetCertificatePrivateKeyPkcs8() []byte {
	if x != nil {
		return x.CertificatePrivateKeyPkcs8
	}
	return nil
}

func (x *GenerateServerCertificatesResponse) GetCertificatePrivateKeyType() KEYTYPE {
	if x != nil {
		return x.CertificatePrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *GenerateServerCertificatesResponse) GetCertificateBundles() []*CertificateBundle {
	if x != nil {
		return x.CertificateBundles
	}
	return nil
}

func (x *GenerateServerCertificatesResponse) GetClientState() *structpb.Struct {
	if x != nil {
		return x.ClientState
	}
	return nil
}

// ServerLedRegistrationRequest is a request for the "operator-led"
// registration flow. Although currently empty it's required to ensure that we
// can add parameters later without an API change.
type ServerLedRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLedRegistrationRequest) Reset() {
	*x = ServerLedRegistrationRequest{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLedRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLedRegistrationRequest) ProtoMessage() {}

func (x *ServerLedRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLedRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ServerLedRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{16}
}

// ServerLedActivationToken contains stored information about a
// one-time-use activation token. The ID is created by the actual returned
// token's nonce HMAC'd by the token's keybytes.
type ServerLedActivationToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The time at which this was created; always overwritten on load from
	// creation_time_marshaled
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=creation_time,proto3" json:"creation_time,omitempty"`
	// This stores a marshaled version of the creation time so that it can easily
	// be wrapped
	CreationTimeMarshaled []byte `protobuf:"bytes,11,opt,name=creation_time_marshaled,proto3" json:"creation_time_marshaled,omitempty"`
	// The private encryption key that will be used with the node after successful
	// activation
	ServerEncryptionPrivateKeyBytes []byte  `protobuf:"bytes,12,opt,name=server_encryption_private_key_bytes,proto3" json:"server_encryption_private_key_bytes,omitempty"`
	ServerEncryptionPrivateKeyType  KEYTYPE `protobuf:"varint,13,opt,name=server_encryption_private_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"server_encryption_private_key_type,omitempty"`
	// Stored challenge information
	RegistrationChallenge      *RegistrationChallenge `protobuf:"bytes,23,opt,name=registration_challenge,proto3" json:"registration_challenge,omitempty"`
	RegistrationChallengeBytes []byte                 `protobuf:"bytes,24,opt,name=registration_challenge_bytes,proto3" json:"registration_challenge_bytes,omitempty"`
	// If set, the key ID of the wrapping key used to encrypt the private keys
	WrappingKeyId string `protobuf:"bytes,30,opt,name=wrapping_key_id,proto3" json:"wrapping_key_id,omitempty"`
	// State is data that the implementor of a Store can use to round-trip data
	// through this library; as an example, a version number on the resource for
	// implementing transactions.
	State         *structpb.Struct `protobuf:"bytes,50,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLedActivationToken) Reset() {
	*x = ServerLedActivationToken{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLedActivationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLedActivationToken) ProtoMessage() {}

func (x *ServerLedActivationToken) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLedActivationToken.ProtoReflect.Descriptor instead.
func (*ServerLedActivationToken) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ServerLedActivationToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerLedActivationToken) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *ServerLedActivationToken) GetCreationTimeMarshaled() []byte {
	if x != nil {
		return x.CreationTimeMarshaled
	}
	return nil
}

func (x *ServerLedActivationToken) GetServerEncryptionPrivateKeyBytes() []byte {
	if x != nil {
		return x.ServerEncryptionPrivateKeyBytes
	}
	return nil
}

func (x *ServerLedActivationToken) GetServerEncryptionPrivateKeyType() KEYTYPE {
	if x != nil {
		return x.ServerEncryptionPrivateKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

func (x *ServerLedActivationToken) GetRegistrationChallenge() *RegistrationChallenge {
	if x != nil {
		return x.RegistrationChallenge
	}
	return nil
}

func (x *ServerLedActivationToken) GetRegistrationChallengeBytes() []byte {
	if x != nil {
		return x.RegistrationChallengeBytes
	}
	return nil
}

func (x *ServerLedActivationToken) GetWrappingKeyId() string {
	if x != nil {
		return x.WrappingKeyId
	}
	return ""
}

func (x *ServerLedActivationToken) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

// ServerLedActivationTokenNonce is the value actually returned to a user.
// The a SHA256-HMAC of the nonce by the key bytes should result in an ID that
// can be found in storage.
type ServerLedActivationTokenNonce struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Nonce                          []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // Equivalent value to Challenge in ServerLedActivationToken
	HmacKeyBytes                   []byte                 `protobuf:"bytes,2,opt,name=hmac_key_bytes,proto3" json:"hmac_key_bytes,omitempty"`
	ActivationTokenId              string                 `protobuf:"bytes,3,opt,name=activation_token_id,proto3" json:"activation_token_id,omitempty"`
	ServerEncryptionPublicKeyBytes []byte                 `protobuf:"bytes,12,opt,name=server_encryption_public_key_bytes,proto3" json:"server_encryption_public_key_bytes,omitempty"`
	ServerEncryptionPublicKeyType  KEYTYPE                `protobuf:"varint,13,opt,name=server_encryption_public_key_type,proto3,enum=github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE" json:"server_encryption_public_key_type,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ServerLedActivationTokenNonce) Reset() {
	*x = ServerLedActivationTokenNonce{}
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLedActivationTokenNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLedActivationTokenNonce) ProtoMessage() {}

func (x *ServerLedActivationTokenNonce) ProtoReflect() protoreflect.Message {
	mi := &file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLedActivationTokenNonce.ProtoReflect.Descriptor instead.
func (*ServerLedActivationTokenNonce) Descriptor() ([]byte, []int) {
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP(), []int{18}
}

func (x *ServerLedActivationTokenNonce) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ServerLedActivationTokenNonce) GetHmacKeyBytes() []byte {
	if x != nil {
		return x.HmacKeyBytes
	}
	return nil
}

func (x *ServerLedActivationTokenNonce) GetActivationTokenId() string {
	if x != nil {
		return x.ActivationTokenId
	}
	return ""
}

func (x *ServerLedActivationTokenNonce) GetServerEncryptionPublicKeyBytes() []byte {
	if x != nil {
		return x.ServerEncryptionPublicKeyBytes
	}
	return nil
}

func (x *ServerLedActivationTokenNonce) GetServerEncryptionPublicKeyType() KEYTYPE {
	if x != nil {
		return x.ServerEncryptionPublicKeyType
	}
	return KEYTYPE_UNSPECIFIED
}

var File_types_github_com_hashicorp_nodeenrollment_types_v1_proto protoreflect.FileDescriptor

const file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDesc = "" +
	"\n" +
	"8types/github.com.hashicorp.nodeenrollment.types.v1.proto\x12,github.com.hashicorp.nodeenrollment.types.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x93\x02\n" +
	"\x11CertificateBundle\x12(\n" +
	"\x0fcertificate_der\x18\x01 \x01(\fR\x0fcertificate_der\x12.\n" +
	"\x12ca_certificate_der\x18\x02 \x01(\fR\x12ca_certificate_der\x12R\n" +
	"\x16certificate_not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x16certificate_not_before\x12P\n" +
	"\x15certificate_not_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15certificate_not_after\"\xfc\x02\n" +
	"\x0fRootCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x0fpublic_key_pkix\x18\x02 \x01(\fR\x0fpublic_key_pkix\x12,\n" +
	"\x11private_key_pkcs8\x18\x04 \x01(\fR\x11private_key_pkcs8\x12a\n" +
	"\x10private_key_type\x18\x05 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x10private_key_type\x12(\n" +
	"\x0fcertificate_der\x18\x06 \x01(\fR\x0fcertificate_der\x12:\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"not_before\x128\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnot_after\"\xa7\x02\n" +
	"\x10RootCertificates\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12W\n" +
	"\acurrent\x18\x02 \x01(\v2=.github.com.hashicorp.nodeenrollment.types.v1.RootCertificateR\acurrent\x12Q\n" +
	"\x04next\x18\x03 \x01(\v2=.github.com.hashicorp.nodeenrollment.types.v1.RootCertificateR\x04next\x12(\n" +
	"\x0fwrapping_key_id\x18\x1e \x01(\tR\x0fwrapping_key_id\x12-\n" +
	"\x05state\x182 \x01(\v2\x17.google.protobuf.StructR\x05state\"\xc3\x02\n" +
	"\rEncryptionKey\x12\x16\n" +
	"\x06key_id\x18\x01 \x01(\tR\x06key_id\x12,\n" +
	"\x11private_key_pkcs8\x18\x02 \x01(\fR\x11private_key_pkcs8\x12a\n" +
	"\x10private_key_type\x18\x03 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x10private_key_type\x12(\n" +
	"\x0fpublic_key_pkix\x18\x04 \x01(\fR\x0fpublic_key_pkix\x12_\n" +
	"\x0fpublic_key_type\x18\x05 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x0fpublic_key_type\"\xe4\n" +
	"\n" +
	"\x0fNodeInformation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12w\n" +
	"\x1bcertificate_public_key_type\x18\x03 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1bcertificate_public_key_type\x12q\n" +
	"\x13certificate_bundles\x18\x06 \x03(\v2?.github.com.hashicorp.nodeenrollment.types.v1.CertificateBundleR\x13certificate_bundles\x12\x18\n" +
	"\anode_id\x18\a \x01(\tR\anode_id\x12R\n" +
	"$previous_certificate_public_key_pkix\x18\t \x01(\fR$previous_certificate_public_key_pkix\x12@\n" +
	"\x1bencryption_public_key_bytes\x18\n" +
	" \x01(\fR\x1bencryption_public_key_bytes\x12u\n" +
	"\x1aencryption_public_key_type\x18\v \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1aencryption_public_key_type\x12P\n" +
	"#server_encryption_private_key_bytes\x18\f \x01(\fR#server_encryption_private_key_bytes\x12\x85\x01\n" +
	"\"server_encryption_private_key_type\x18\r \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\"server_encryption_private_key_type\x12.\n" +
	"\x12registration_nonce\x18\x14 \x01(\fR\x12registration_nonce\x12{\n" +
	"\x16registration_challenge\x18\x17 \x01(\v2C.github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallengeR\x16registration_challenge\x12\x94\x01\n" +
	"\x1fwrapping_registration_flow_info\x18\x16 \x01(\v2J.github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfoR\x1fwrapping_registration_flow_info\x12(\n" +
	"\x0fwrapping_key_id\x18\x1e \x01(\tR\x0fwrapping_key_id\x12-\n" +
	"\x05state\x182 \x01(\v2\x17.google.protobuf.StructR\x05state\x12u\n" +
	"\x17previous_encryption_key\x18< \x01(\v2;.github.com.hashicorp.nodeenrollment.types.v1.EncryptionKeyR\x17previous_encryption_key\"\x83\x01\n" +
	"\x12NodeInformationSet\x12\x18\n" +
	"\anode_id\x18\a \x01(\tR\anode_id\x12S\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2=.github.com.hashicorp.nodeenrollment.types.v1.NodeInformationR\x05nodes\"5\n" +
	"\x15RegistrationChallenge\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"\xc7\n" +
	"\n" +
	"\x0fNodeCredentials\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12D\n" +
	"\x1dcertificate_private_key_pkcs8\x18\x04 \x01(\fR\x1dcertificate_private_key_pkcs8\x12y\n" +
	"\x1ccertificate_private_key_type\x18\x05 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1ccertificate_private_key_type\x12q\n" +
	"\x13certificate_bundles\x18\x06 \x03(\v2?.github.com.hashicorp.nodeenrollment.types.v1.CertificateBundleR\x13certificate_bundles\x12R\n" +
	"$previous_certificate_public_key_pkix\x18\t \x01(\fR$previous_certificate_public_key_pkix\x12B\n" +
	"\x1cencryption_private_key_bytes\x18\n" +
	" \x01(\fR\x1cencryption_private_key_bytes\x12w\n" +
	"\x1bencryption_private_key_type\x18\v \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1bencryption_private_key_type\x12N\n" +
	"\"server_encryption_public_key_bytes\x18\f \x01(\fR\"server_encryption_public_key_bytes\x12\x83\x01\n" +
	"!server_encryption_public_key_type\x18\r \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER!server_encryption_public_key_type\x12.\n" +
	"\x12registration_nonce\x18\x14 \x01(\fR\x12registration_nonce\x12{\n" +
	"\x16registration_challenge\x18\x17 \x01(\v2C.github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallengeR\x16registration_challenge\x12J\n" +
	" encrypted_registration_challenge\x18\x18 \x01(\fR encrypted_registration_challenge\x12(\n" +
	"\x0fwrapping_key_id\x18\x1e \x01(\tR\x0fwrapping_key_id\x12-\n" +
	"\x05state\x182 \x01(\v2\x17.google.protobuf.StructR\x05state\x12u\n" +
	"\x17previous_encryption_key\x18< \x01(\v2;.github.com.hashicorp.nodeenrollment.types.v1.EncryptionKeyR\x17previous_encryption_key\"\x87\x02\n" +
	"\x1cWrappingRegistrationFlowInfo\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12\x14\n" +
	"\x05nonce\x18\x14 \x01(\fR\x05nonce\x126\n" +
	"\x16registration_challenge\x18\x17 \x01(\fR\x16registration_challenge\x12W\n" +
	"\x1bapplication_specific_params\x182 \x01(\v2\x17.google.protobuf.StructR\x19applicationSpecificParams\"\xce\b\n" +
	"\x18FetchNodeCredentialsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12w\n" +
	"\x1bcertificate_public_key_type\x18\x03 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1bcertificate_public_key_type\x12R\n" +
	"$previous_certificate_public_key_pkix\x18\t \x01(\fR$previous_certificate_public_key_pkix\x12@\n" +
	"\x1bencryption_public_key_bytes\x18\n" +
	" \x01(\fR\x1bencryption_public_key_bytes\x12u\n" +
	"\x1aencryption_public_key_type\x18\v \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1aencryption_public_key_type\x12\x14\n" +
	"\x05nonce\x18\x14 \x01(\fR\x05nonce\x12{\n" +
	"\x16registration_challenge\x18\x17 \x01(\v2C.github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallengeR\x16registration_challenge\x12J\n" +
	" encrypted_registration_challenge\x18\x18 \x01(\fR encrypted_registration_challenge\x120\n" +
	"\x13activation_token_id\x18\x19 \x01(\tR\x13activation_token_id\x12<\n" +
	"\x19wrapped_registration_info\x18\x15 \x01(\fR\x19wrapped_registration_info\x12\x94\x01\n" +
	"\x1fwrapping_registration_flow_info\x18\x16 \x01(\v2J.github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfoR\x1fwrapping_registration_flow_info\x12:\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"not_before\x128\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnot_after\"\xed\x01\n" +
	"\x1bFetchNodeCredentialsRequest\x12\x16\n" +
	"\x06bundle\x18\x1c \x01(\fR\x06bundle\x12*\n" +
	"\x10bundle_signature\x18\x1d \x01(\fR\x10bundle_signature\x12\\\n" +
	")rewrapped_wrapping_registration_flow_info\x18  \x01(\fR)rewrapped_wrapping_registration_flow_info\x12,\n" +
	"\x11rewrapping_key_id\x18! \x01(\tR\x11rewrapping_key_id\"\xa5\x02\n" +
	"\x1cFetchNodeCredentialsResponse\x12G\n" +
	"\"server_encryption_public_key_bytes\x18\f \x01(\fR\x1bencryption_public_key_bytes\x12|\n" +
	"!server_encryption_public_key_type\x18\r \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1aencryption_public_key_type\x12>\n" +
	"\x1aencrypted_node_credentials\x18( \x01(\fR\x1aencrypted_node_credentials\"\xd6\x01\n" +
	"\x1cRotateNodeCredentialsRequest\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12\x18\n" +
	"\anode_id\x18\a \x01(\tR\anode_id\x12Z\n" +
	"(encrypted_fetch_node_credentials_request\x18- \x01(\fR(encrypted_fetch_node_credentials_request\"}\n" +
	"\x1dRotateNodeCredentialsResponse\x12\\\n" +
	")encrypted_fetch_node_credentials_response\x18- \x01(\fR)encrypted_fetch_node_credentials_response\"\xeb\x02\n" +
	"!GenerateServerCertificatesRequest\x12@\n" +
	"\x1bcertificate_public_key_pkix\x18\x02 \x01(\fR\x1bcertificate_public_key_pkix\x12\x18\n" +
	"\anode_id\x18\a \x01(\tR\anode_id\x12\x14\n" +
	"\x05nonce\x18\x14 \x01(\fR\x05nonce\x12(\n" +
	"\x0fnonce_signature\x18\x15 \x01(\fR\x0fnonce_signature\x12 \n" +
	"\vcommon_name\x18\x18 \x01(\tR\vcommon_name\x12,\n" +
	"\x11skip_verification\x18\x19 \x01(\bR\x11skip_verification\x12\"\n" +
	"\fclient_state\x182 \x01(\fR\fclient_state\x126\n" +
	"\x16client_state_signature\x183 \x01(\fR\x16client_state_signature\"\x95\x03\n" +
	"\"GenerateServerCertificatesResponse\x12D\n" +
	"\x1dcertificate_private_key_pkcs8\x18\x04 \x01(\fR\x1dcertificate_private_key_pkcs8\x12y\n" +
	"\x1ccertificate_private_key_type\x18\x05 \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\x1ccertificate_private_key_type\x12q\n" +
	"\x13certificate_bundles\x18\x06 \x03(\v2?.github.com.hashicorp.nodeenrollment.types.v1.CertificateBundleR\x13certificate_bundles\x12;\n" +
	"\fclient_state\x182 \x01(\v2\x17.google.protobuf.StructR\fclient_state\"\x1e\n" +
	"\x1cServerLedRegistrationRequest\"\x9a\x05\n" +
	"\x18ServerLedActivationToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\rcreation_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rcreation_time\x128\n" +
	"\x17creation_time_marshaled\x18\v \x01(\fR\x17creation_time_marshaled\x12P\n" +
	"#server_encryption_private_key_bytes\x18\f \x01(\fR#server_encryption_private_key_bytes\x12\x85\x01\n" +
	"\"server_encryption_private_key_type\x18\r \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER\"server_encryption_private_key_type\x12{\n" +
	"\x16registration_challenge\x18\x17 \x01(\v2C.github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallengeR\x16registration_challenge\x12B\n" +
	"\x1cregistration_challenge_bytes\x18\x18 \x01(\fR\x1cregistration_challenge_bytes\x12(\n" +
	"\x0fwrapping_key_id\x18\x1e \x01(\tR\x0fwrapping_key_id\x12-\n" +
	"\x05state\x182 \x01(\v2\x17.google.protobuf.StructR\x05state\"\xe5\x02\n" +
	"\x1dServerLedActivationTokenNonce\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12&\n" +
	"\x0ehmac_key_bytes\x18\x02 \x01(\fR\x0ehmac_key_bytes\x120\n" +
	"\x13activation_token_id\x18\x03 \x01(\tR\x13activation_token_id\x12N\n" +
	"\"server_encryption_public_key_bytes\x18\f \x01(\fR\"server_encryption_public_key_bytes\x12\x83\x01\n" +
	"!server_encryption_public_key_type\x18\r \x01(\x0e25.github.com.hashicorp.nodeenrollment.types.v1.KEYTYPER!server_encryption_public_key_type*3\n" +
	"\aKEYTYPE\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aED25519\x10\x01\x12\n" +
	"\n" +
	"\x06X25519\x10\x02B+Z)github.com/hashicorp/nodeenrollment/typesb\x06proto3"

var (
	file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescOnce sync.Once
	file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescData []byte
)

func file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescGZIP() []byte {
	file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescOnce.Do(func() {
		file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDesc), len(file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDesc)))
	})
	return file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDescData
}

var file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_goTypes = []any{
	(KEYTYPE)(0),                               // 0: github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	(*CertificateBundle)(nil),                  // 1: github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle
	(*RootCertificate)(nil),                    // 2: github.com.hashicorp.nodeenrollment.types.v1.RootCertificate
	(*RootCertificates)(nil),                   // 3: github.com.hashicorp.nodeenrollment.types.v1.RootCertificates
	(*EncryptionKey)(nil),                      // 4: github.com.hashicorp.nodeenrollment.types.v1.EncryptionKey
	(*NodeInformation)(nil),                    // 5: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation
	(*NodeInformationSet)(nil),                 // 6: github.com.hashicorp.nodeenrollment.types.v1.NodeInformationSet
	(*RegistrationChallenge)(nil),              // 7: github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallenge
	(*NodeCredentials)(nil),                    // 8: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials
	(*WrappingRegistrationFlowInfo)(nil),       // 9: github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfo
	(*FetchNodeCredentialsInfo)(nil),           // 10: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo
	(*FetchNodeCredentialsRequest)(nil),        // 11: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsRequest
	(*FetchNodeCredentialsResponse)(nil),       // 12: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsResponse
	(*RotateNodeCredentialsRequest)(nil),       // 13: github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsRequest
	(*RotateNodeCredentialsResponse)(nil),      // 14: github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsResponse
	(*GenerateServerCertificatesRequest)(nil),  // 15: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesRequest
	(*GenerateServerCertificatesResponse)(nil), // 16: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse
	(*ServerLedRegistrationRequest)(nil),       // 17: github.com.hashicorp.nodeenrollment.types.v1.ServerLedRegistrationRequest
	(*ServerLedActivationToken)(nil),           // 18: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationToken
	(*ServerLedActivationTokenNonce)(nil),      // 19: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationTokenNonce
	(*timestamppb.Timestamp)(nil),              // 20: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                    // 21: google.protobuf.Struct
}
var file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_depIdxs = []int32{
	20, // 0: github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle.certificate_not_before:type_name -> google.protobuf.Timestamp
	20, // 1: github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle.certificate_not_after:type_name -> google.protobuf.Timestamp
	0,  // 2: github.com.hashicorp.nodeenrollment.types.v1.RootCertificate.private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	20, // 3: github.com.hashicorp.nodeenrollment.types.v1.RootCertificate.not_before:type_name -> google.protobuf.Timestamp
	20, // 4: github.com.hashicorp.nodeenrollment.types.v1.RootCertificate.not_after:type_name -> google.protobuf.Timestamp
	2,  // 5: github.com.hashicorp.nodeenrollment.types.v1.RootCertificates.current:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RootCertificate
	2,  // 6: github.com.hashicorp.nodeenrollment.types.v1.RootCertificates.next:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RootCertificate
	21, // 7: github.com.hashicorp.nodeenrollment.types.v1.RootCertificates.state:type_name -> google.protobuf.Struct
	0,  // 8: github.com.hashicorp.nodeenrollment.types.v1.EncryptionKey.private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 9: github.com.hashicorp.nodeenrollment.types.v1.EncryptionKey.public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 10: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.certificate_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	1,  // 11: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.certificate_bundles:type_name -> github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle
	0,  // 12: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.encryption_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 13: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.server_encryption_private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	7,  // 14: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.registration_challenge:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallenge
	9,  // 15: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.wrapping_registration_flow_info:type_name -> github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfo
	21, // 16: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.state:type_name -> google.protobuf.Struct
	4,  // 17: github.com.hashicorp.nodeenrollment.types.v1.NodeInformation.previous_encryption_key:type_name -> github.com.hashicorp.nodeenrollment.types.v1.EncryptionKey
	5,  // 18: github.com.hashicorp.nodeenrollment.types.v1.NodeInformationSet.nodes:type_name -> github.com.hashicorp.nodeenrollment.types.v1.NodeInformation
	0,  // 19: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.certificate_private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	1,  // 20: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.certificate_bundles:type_name -> github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle
	0,  // 21: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.encryption_private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 22: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.server_encryption_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	7,  // 23: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.registration_challenge:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallenge
	21, // 24: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.state:type_name -> google.protobuf.Struct
	4,  // 25: github.com.hashicorp.nodeenrollment.types.v1.NodeCredentials.previous_encryption_key:type_name -> github.com.hashicorp.nodeenrollment.types.v1.EncryptionKey
	21, // 26: github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfo.application_specific_params:type_name -> google.protobuf.Struct
	0,  // 27: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.certificate_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 28: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.encryption_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	7,  // 29: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.registration_challenge:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallenge
	9,  // 30: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.wrapping_registration_flow_info:type_name -> github.com.hashicorp.nodeenrollment.types.v1.WrappingRegistrationFlowInfo
	20, // 31: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.not_before:type_name -> google.protobuf.Timestamp
	20, // 32: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsInfo.not_after:type_name -> google.protobuf.Timestamp
	0,  // 33: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsResponse.server_encryption_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	0,  // 34: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse.certificate_private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	1,  // 35: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse.certificate_bundles:type_name -> github.com.hashicorp.nodeenrollment.types.v1.CertificateBundle
	21, // 36: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse.client_state:type_name -> google.protobuf.Struct
	20, // 37: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationToken.creation_time:type_name -> google.protobuf.Timestamp
	0,  // 38: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationToken.server_encryption_private_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	7,  // 39: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationToken.registration_challenge:type_name -> github.com.hashicorp.nodeenrollment.types.v1.RegistrationChallenge
	21, // 40: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationToken.state:type_name -> google.protobuf.Struct
	0,  // 41: github.com.hashicorp.nodeenrollment.types.v1.ServerLedActivationTokenNonce.server_encryption_public_key_type:type_name -> github.com.hashicorp.nodeenrollment.types.v1.KEYTYPE
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_init() }
func file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_init() {
	if File_types_github_com_hashicorp_nodeenrollment_types_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDesc), len(file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_goTypes,
		DependencyIndexes: file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_depIdxs,
		EnumInfos:         file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_enumTypes,
		MessageInfos:      file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_msgTypes,
	}.Build()
	File_types_github_com_hashicorp_nodeenrollment_types_v1_proto = out.File
	file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_goTypes = nil
	file_types_github_com_hashicorp_nodeenrollment_types_v1_proto_depIdxs = nil
}
