// Copyright IBM Corp. 2022, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: multihop/github.com.hashicorp.nodeenrollment.multihop.v1.proto

package multihop

import (
	types "github.com/hashicorp/nodeenrollment/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto protoreflect.FileDescriptor

const file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_rawDesc = "" +
	"\n" +
	">multihop/github.com.hashicorp.nodeenrollment.multihop.v1.proto\x12/github.com.hashicorp.nodeenrollment.multihop.v1\x1a8types/github.com.hashicorp.nodeenrollment.types.v1.proto2\xbc\x04\n" +
	"\x0fMultihopService\x12\xaf\x01\n" +
	"\x14FetchNodeCredentials\x12I.github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsRequest\x1aJ.github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsResponse\"\x00\x12\xc1\x01\n" +
	"\x1aGenerateServerCertificates\x12O.github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesRequest\x1aP.github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse\"\x00\x12\xb2\x01\n" +
	"\x15RotateNodeCredentials\x12J.github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsRequest\x1aK.github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsResponse\"\x00B.Z,github.com/hashicorp/nodeenrollment/multihopb\x06proto3"

var file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_goTypes = []any{
	(*types.FetchNodeCredentialsRequest)(nil),        // 0: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsRequest
	(*types.GenerateServerCertificatesRequest)(nil),  // 1: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesRequest
	(*types.RotateNodeCredentialsRequest)(nil),       // 2: github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsRequest
	(*types.FetchNodeCredentialsResponse)(nil),       // 3: github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsResponse
	(*types.GenerateServerCertificatesResponse)(nil), // 4: github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse
	(*types.RotateNodeCredentialsResponse)(nil),      // 5: github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsResponse
}
var file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_depIdxs = []int32{
	0, // 0: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.FetchNodeCredentials:input_type -> github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsRequest
	1, // 1: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.GenerateServerCertificates:input_type -> github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesRequest
	2, // 2: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.RotateNodeCredentials:input_type -> github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsRequest
	3, // 3: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.FetchNodeCredentials:output_type -> github.com.hashicorp.nodeenrollment.types.v1.FetchNodeCredentialsResponse
	4, // 4: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.GenerateServerCertificates:output_type -> github.com.hashicorp.nodeenrollment.types.v1.GenerateServerCertificatesResponse
	5, // 5: github.com.hashicorp.nodeenrollment.multihop.v1.MultihopService.RotateNodeCredentials:output_type -> github.com.hashicorp.nodeenrollment.types.v1.RotateNodeCredentialsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_init() }
func file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_init() {
	if File_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_rawDesc), len(file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_goTypes,
		DependencyIndexes: file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_depIdxs,
	}.Build()
	File_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto = out.File
	file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_goTypes = nil
	file_multihop_github_com_hashicorp_nodeenrollment_multihop_v1_proto_depIdxs = nil
}
